# Uncomment this line to define a global platform for your project
source 'https://github.com/Transparentmask/PrivateSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

target 'ABase' do

#pod 'LTFramework', :git => 'http://git.lngtop.com/RD-iOS/LTFramework.git'
pod 'MVJGProgressHUD', '~> 1.3.0’
pod 'RMUniversalAlert'
pod 'SDWebImage', '~> 3.7'
pod 'AFNetworking', '~> 3.0'
pod 'MVTheme', '~> 0.0.3'
pod 'MVRBStoryboardLink', '~> 0.1.5'
pod 'Mantle', '~> 2.0'
pod 'hpple'
#pod 'UIActivityIndicator-for-SDWebImage'
#pod 'SYPhotoBrowser'

#target 'ABase' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ABase

end
